### PR TITLE
PR for solving the conflicts and unified the command management

### PR DESCRIPTION
**Pull request by jayceguo**
I fixed some conflict issues based on your latest commit. Also, I unified the `command` management. With this said, if you want to add any command, you could simply add a new command class in `controller.TwitchCommands` and extends `TwitchCommandContract`, and then load it in `TwitchAPI`'s `loadedCommandList` list.

These changes should be good to push it to the main repo, I hope you could pr it asap before anyone else is trying to merge more into the main repo, which might cause more conflicts.

Currently, I am facing some issues with the `dotenv` feature, which the `Source.fromResource` is not correctly loading the `.env` file, I am still trying to fix it.

Have fun with this project, and have a good night, this should be my latest commit tonight.

### CODE REVIEW

**Comment by jayceguo** [comment]
removed `resources` from pom.xml, which messed up with the dotenv config loading.
If the project is still not reading the dotenv config, please re-sync the maven settings.

**Review by epicseven-cup — APPROVED** [review]
Thank you!

**Comment by Y2Nk4** [comment]
I recommend to pr it the the main repo asap to prevent further conflicts fron other contributors.

**Comment by jayceguo** [comment]
I will pr it to the main repo since the `dotenv` is urgent to be fixed, but with this, your repo still remains to be the latest version, so you don't need to worry about any other conflicts.

**Comment by epicseven-cup** [comment]
got it I will pr it right now

**Comment by jayceguo** [comment]
Nah, I have already pr it, let's wait for Jesse to merge it, you can check it here https://github.com/UB-CSE/RoboTA/pull/5

**Comment by epicseven-cup** [comment]
thanks bro just need to wait for jesse

**Comment by jayceguo** [comment]
Np, bro, I need to do my mth hw now, lol.

**Comment by jayceguo** [comment]
I commented out your codes in `HelpCommand` since you are still investigating how the line break work in twitch. You could add it once you find that out. 
Also, I exposed a `sendRawMessageInChat` method from the `TwitchAPI` class, the example of how to use it could be found on the `PriestChecker` class.

**Comment by epicseven-cup** [comment]
Got it same here need to study for math also xD

**Pull request merged**
